# Generated by Django 3.2.5 on 2021-07-07 18:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_at',

            field=models.DateTimeField(default=datetime.datetime(2021, 7, 7, 18, 48, 34, 53373)),
        ),
    ]
