# Generated by Django 3.1.7 on 2021-07-07 19:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0003_auto_20210707_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 7, 19, 0, 49, 181715)),
        ),
    ]
